version: "3.8"

services:
  frontend:
    build: frontend
    environment:
      - REACT_APP_BACKEND=http://localhost:5000
    ports:
      - "3000:3000"
    entrypoint:
      - yarn
      - run
      - start
    volumes:
      - "./frontend:/app/frontend/"
    networks:
      - central

  backend:
    build: backend
    environment:
      - PORT=5000
    entrypoint:
      - yarn
      - run
      - start
    volumes:
      - "./backend:/app/backend/"
    ports:
      - "5000:5000"
    networks:
      - central

networks:
  central:
